### ISSUE TITLE
Bug 无法实例化Config

### ISSUE THREAD

**Issue by dmf-code** [luoxiaojun1992/laravel-tars#17]
```
Class config does not exist|
#0 /data/tars/tarsnode-data/Activity.groupBuy/bin/src/vendor/laravel/framework/src/Illuminate/Container/Container.php(752): ReflectionClass->__construct('config') 
#1 /data/tars/tarsnode-data/Activity.groupBuy/bin/src/vendor/laravel/framework/src/Illuminate/Container/Container.php(631): Illuminate\Container\Container->build('config') 
#2 /data/tars/tarsnode-data/Activity.groupBuy/bin/src/vendor/laravel/framework/src/Illuminate/Container/Container.php(586): Illuminate\Container\Container->resolve('config', Array) 
#3 /data/tars/tarsnode-data/Activity.groupBuy/bin/src/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(732): Illuminate\Container\Container->make('config', Array) 
#4 /data/tars/tarsnode-data/Activity.groupBuy/bin/src/vendor/laravel/framework/src/Illuminate/Foundation/helpers.php(110): Illuminate\Foundation\Application->make('config', Array) 
#5 /data/tars/tarsnode-data/Activity.groupBuy/bin/src/vendor/laravel/framework/src/Illuminate/Foundation/helpers.php(269): app('config') 
#6 /data/tars/tarsnode-data/Activity.groupBuy/bin/src/vendor/luoxiaojun1992/laravel-tars/src/App.php(28): config(Array) 
#7 /data/tars/tarsnode-data/Activity.groupBuy/bin/src/vendor/luoxiaojun1992/laravel-tars/src/Route/TarsRoute.php(166): Lxj\Laravel\Tars\App::getApp() 
#8 /data/tars/tarsnode-data/Activity.groupBuy/bin/src/vendor/luoxiaojun1992/laravel-tars/src/Route/TarsRoute.php(120): Lxj\Laravel\Tars\Route\TarsRoute->app() 
#9 /data/tars/tarsnode-data/Activity.groupBuy/bin/src/vendor/luoxiaojun1992/laravel-tars/src/Route/TarsRoute.php(26): Lxj\Laravel\Tars\Route\TarsRoute->clean() 
#10 /data/tars/tarsnode-data/Activity.groupBuy/bin/src/vendor/phptars/tars-server/src/protocol/HTTPProtocol.php(35): Lxj\Laravel\Tars\Route\TarsRoute->dispatch(Object(Tars\core\Request), Object(Tars\core\Response)) 
#11 /data/tars/tarsnode-data/Activity.groupBuy/bin/src/vendor/phptars/tars-server/src/core/Server.php(683): Tars\protocol\HTTPProtocol->route(Object(Tars\core\Request), Object(Tars\core\Response)) 
#12 {main}

```

![image](https://user-images.githubusercontent.com/22268578/90951233-8b7c7d00-e48b-11ea-951f-8479e56cfa57.png)
这个 `config` 报错了

刷新第二次页面就出现这个问题了，上面的错误就没有了
```
Class cookie does not exist|#0 /data/tars/tarsnode-data/Activity.groupBuy/bin/src/vendor/laravel/framework/src/Illuminate/Container/Container.php(752): ReflectionClass->__construct('cookie') 
#1 /data/tars/tarsnode-data/Activity.groupBuy/bin/src/vendor/laravel/framework/src/Illuminate/Container/Container.php(631): Illuminate\Container\Container->build('cookie') 
#2 /data/tars/tarsnode-data/Activity.groupBuy/bin/src/vendor/laravel/framework/src/Illuminate/Container/Container.php(586): Illuminate\Container\Container->resolve('cookie', Array) 
#3 /data/tars/tarsnode-data/Activity.groupBuy/bin/src/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(732): Illuminate\Container\Container->make('cookie', Array) 
#4 /data/tars/tarsnode-data/Activity.groupBuy/bin/src/vendor/luoxiaojun1992/laravel-tars/src/Route/TarsRoute.php(145): Illuminate\Foundation\Application->make('cookie') 
#5 /data/tars/tarsnode-data/Activity.groupBuy/bin/src/vendor/luoxiaojun1992/laravel-tars/src/Route/TarsRoute.php(26): Lxj\Laravel\Tars\Route\TarsRoute->clean() 
#6 /data/tars/tarsnode-data/Activity.groupBuy/bin/src/vendor/phptars/tars-server/src/protocol/HTTPProtocol.php(35): Lxj\Laravel\Tars\Route\TarsRoute->dispatch(Object(Tars\core\Request), Object(Tars\core\Response)) 
#7 /data/tars/tarsnode-data/Activity.groupBuy/bin/src/vendor/phptars/tars-server/src/core/Server.php(683): Tars\protocol\HTTPProtocol->route(Object(Tars\core\Request), Object(Tars\core\Response))
 #8 {main}
```

框架搭建是使用 `laravel-tars-demo` 这个的，然后 `composer install` 后就变成这样子了

![image](https://user-images.githubusercontent.com/22268578/90951683-77d31580-e48f-11ea-9afc-91c8b3840a4e.png)
注释掉这段代码就能够进去了
![image](https://user-images.githubusercontent.com/22268578/90951687-891c2200-e48f-11ea-917e-bb1b096050da.png)
但是还是存在着服务启动第一次请求，会返回 `config` 无法实例化错误问题 

```
$reflector = new ReflectionClass($concrete);
```

这里的 `$concrete='config'` 然后无法实例化，因为这个 `config` 不是命名空间，导致无法实例化。
![image](https://user-images.githubusercontent.com/22268578/90952690-3c891480-e498-11ea-8e75-96f0af374a87.png)
这样子就不报错了，应该是别名使用上出问题了

**Comment by luoxiaojun1992** [comment]
感谢反馈，可能是app没有boot的原因，请更新下composer包后再测试下，谢谢

**Comment by dmf-code** [comment]
> 感谢反馈，可能是app没有boot的原因，请更新下composer包后再测试下，谢谢

```

PHP Fatal error: Uncaught TypeError: Argument 2 passed to Illuminate\Routing\UrlGenerator::__construct() must be an instance of Illuminate\Http\Request, null given, called in /data/tars/tarsnode-data/Activity.groupBuy/bin/src/vendor/laravel/framework/src/Illuminate/Routing/RoutingServiceProvider.php on line 67 and defined in /data/tars/tarsnode-data/Activity.groupBuy/bin/src/vendor/laravel/framework/src/Illuminate/Routing/UrlGenerator.php:102
--
  | Stack trace:
  | #0 /data/tars/tarsnode-data/Activity.groupBuy/bin/src/vendor/laravel/framework/src/Illuminate/Routing/RoutingServiceProvider.php(67): Illuminate\Routing\UrlGenerator->__construct(Object(Illuminate\Routing\RouteCollection), NULL)
  | #1 /data/tars/tarsnode-data/Activity.groupBuy/bin/src/vendor/laravel/framework/src/Illuminate/Container/Container.php(749): Illuminate\Routing\RoutingServiceProvider->Illuminate\Routing\{closure}(Object(Illuminate\Foundation\Application), Array)
  | #2 /data/tars/tarsnode-data/Activity.groupBuy/bin/src/vendor/laravel/framework/src/Illuminate/Container/Co in /data/tars/tarsnode-data/Activity.groupBuy/bin/src/vendor/laravel/framework/src/Illuminate/Routing/UrlGenerator.php on line 102
  |  
  | In UrlGenerator.php line 102:
  |  
  | Uncaught TypeError: Argument 2 passed to Illuminate\Routing\UrlGenerator::_
  | _construct() must be an instance of Illuminate\Http\Request, null given, ca
  | lled in /data/tars/tarsnode-data/Activity.groupBuy/bin/src/vendor/laravel/f
  | ramework/src/Illuminate/Routing/RoutingServiceProvider.php on line 67 and d
  | efined in /data/tars/tarsnode-data/Activity.groupBuy/bin/src/vendor/laravel
  | /framework/src/Illuminate/Routing/UrlGenerator.php:102
  | Stack trace:
  | #0 /data/tars/tarsnode-data/Activity.groupBuy/bin/src/vendor/laravel/framew
  | ork/src/Illuminate/Routing/RoutingServiceProvider.php(67): Illuminate\Routi
  | ng\UrlGenerator->__construct(Object(Illuminate\Routing\RouteCollection), NU
  | LL)
  | #1 /data/tars/tarsnode-data/Activity.groupBuy/bin/src/vendor/laravel/framew
  | ork/src/Illuminate/Container/Container.php(749): Illuminate\Routing\Routing
  | ServiceProvider->Illuminate\Routing\{closure}(Object(Illuminate\Foundation\
  | Application), Array)
  | #2 /data/tars/tarsnode-data/Activity.groupBuy/bin/src/vendor/laravel/framew
  | ork/src/Illuminate/Container/Co
  |  
  |  
  |  
  | In UrlGenerator.php line 102:
  |  
  | Uncaught TypeError: Argument 2 passed to Illuminate\Routing\UrlGenerator::_
  | _construct() must be an instance of Illuminate\Http\Request, null given, ca
  | lled in /data/tars/tarsnode-data/Activity.groupBuy/bin/src/vendor/laravel/f
  | ramework/src/Illuminate/Routing/RoutingServiceProvider.php on line 67 and d
  | efined in /data/tars/tarsnode-data/Activity.groupBuy/bin/src/vendor/laravel
  | /framework/src/Illuminate/Routing/UrlGenerator.php:102
  | Stack trace:
  | #0 /data/tars/tarsnode-data/Activity.groupBuy/bin/src/vendor/laravel/framew
  | ork/src/Illuminate/Routing/RoutingServiceProvider.php(67): Illuminate\Routi
  | ng\UrlGenerator->__construct(Object(Illuminate\Routing\RouteCollection), NU
  | LL)
  | #1 /data/tars/tarsnode-data/Activity.groupBuy/bin/src/vendor/laravel/framew
  | ork/src/Illuminate/Container/Container.php(749): Illuminate\Routing\Routing
  | ServiceProvider->Illuminate\Routing\{closure}(Object(Illuminate\Foundation\
  | Application), Array)
  | #2 /data/tars/tarsnode-data/Activity.groupBuy/bin/src/vendor/laravel/framew
  | ork/src/Illuminate/Container/Co
  |  
  |  
  | [2020-08-22 17:55:32 *4866.2] ERROR php_swoole_server_rshutdown (ERRNO 503): Fatal error: Uncaught TypeError: Argument 2 passed to Illuminate\Routing\UrlGenerator::__construct() must be an instance of Illuminate\Http\Request, null given, called in /data/tars/tarsnode-data/Activity.groupBuy/bin/src/vendor/laravel/framework/src/Illuminate/Routing/RoutingServiceProvider.php on line 67 and defined in /data/tars/tarsnode-data/Activity.groupBuy/bin/src/vendor/laravel/framework/src/Illuminate/Routing/UrlGenerator.php:102
  | Stack trace:
  | #0 /data/tars/tarsnode-data/Activity.groupBuy/bin/src/vendor/laravel/framework/src/Illuminate/Routing/RoutingServiceProvider.php(67): Illuminate\Routing\UrlGenerator->__construct(Object(Illuminate\Routing\RouteCollection), NULL)
  | #1 /data/tars/tarsnode-data/Activity.groupBuy/bin/src/vendor/laravel/framework/src/Illuminate/Container/Container.php(749): Illuminate\Routing\RoutingServiceProvider->Illuminate\Routing\{closure}(Object(Illuminate\Foundation\Application), Array)
  | #2 /data/tars/tarsnode-data/Activity.groupBuy/bin/src/vendor/laravel/framework/src/Illuminate/Container/Co in /data/tars/tarsnode-data/Activity.groupBuy/bin/src/vendor/laravel/framework/src/Illuminate/Routing/UrlGenerator.php on line 102


```

更新后 又有新问题了

**Comment by luoxiaojun1992** [comment]
稍等，我再看看

**Comment by luoxiaojun1992** [comment]
@dmf-code 请更新下composer包后再测试下，谢谢

**Comment by dmf-code** [comment]
可以使用了，感谢
